framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    serializer:
#        enable_annotations: false
        mapping:
            paths: ['%kernel.project_dir%/config/serialization/']
