framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    serializer:
        mapping:
            paths: ['%kernel.project_dir%/config/serializer']

    php_errors:
        log: true
