version: '3.4'

services:
  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./:/srv/api:rw,cached

  nginx:
    image: nginx:1.17.5
    container_name: nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/api:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - php

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ubi-root
      MYSQL_DATABASE: ubitransport
      MYSQL_USER: ubitransport
      MYSQL_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/mysql
