App\Entity\Student:
  attributes:
      normalization_context:
          groups: ['student:read']
      denormalization_context:
          groups: ['student:write']

  itemOperations:
      get: ~
      put: ~
      delete: ~
      average:
          method: GET
          path: /students/{id}/average
          controller: App\Controller\StudentAverage
          openapi_context:
              summary: Get the student's average
              parameters:
                - in: path
                  name: id
